SHELL := /bin/bash

# `make serve` to serve the mkdocs site on localhost.
.PHONY: serve
serve:
	mkdocs serve

# `make build` to build the static documentation site.
.PHONY: build
build:
	mkdocs build

# `make clean` cleans everything up.
.PHONY: clean
clean:
	rm -rf site
